### PR TITLE
new changes

### PR DESCRIPTION
**Pull request by matheusperez**
- name floatingActionButton changed to floatingWidget
- Remove marginRight
- dynamic floatingWidget position
- Exemple Two

### CODE REVIEW

**Comment by MarcinusX** [comment]
Hey Matheus! Thanks for the pull request, would you mind adding me to the forked repo so that I can add a few adjustments to your code and then merge it?

**Comment by Matheus-Perez** [comment]
No, no problem: D
You can make adjustments

**Comment by MarcinusX** [comment]
I think I need you to invite me to your project then :)

**Comment by Matheus-Perez** [comment]
Oops haha ​​I'm noob yet, I already invited you to the project

**Comment by MarcinusX** [comment]
Check it out now and if you like it, then I will merge and publish today or tomorrow :)

**Comment by MarcinusX** [comment]
Merged and published on Pub :) Thank you for your contribution :)

**Pull request merged**
